function toggleNav(){document.querySelector('.sidebar')?.classList.toggle('open')}
function addLeadContactActions(){const actions=document.querySelector('.actions');const call=actions?.querySelector('a[href^="tel:"]');if(!actions||!call)return;const phone=call.getAttribute('href').replace(/^tel:/,'').replace(/[^0-9]/g,'');if(/^[0-9]{8,15}$/.test(phone)&&!actions.querySelector('.whatsapp-link')){const link=document.createElement('a');link.className='btn btn-success whatsapp-link';link.target='_blank';link.rel='noopener';link.href='https://wa.me/'+phone;link.textContent='WhatsApp';actions.insertBefore(link,actions.firstChild?.nextSibling)}const email=document.querySelector('input[name="email"]')?.value.trim();const match=window.location.pathname.match(/^\/leads\/(\d+)$/);if(email&&match&&!actions.querySelector('.email-link')){const link=document.createElement('a');link.className='btn btn-primary email-link';link.href='/leads/'+match[1]+'/send-email';link.textContent='Send Email';actions.appendChild(link)}}
function addExportActions(){if(!['/leads','/import'].includes(window.location.pathname))return;const toolbar=document.querySelector('.toolbar');if(!toolbar||toolbar.querySelector('.export-actions'))return;const group=document.createElement('div');group.className='actions export-actions';[['csv','Export CSV','btn-light'],['xlsx','Export Excel','btn-primary']].forEach(([format,label,style])=>{const link=document.createElement('a');link.className='btn '+style+' btn-sm';link.href='/export/leads?format='+format;link.textContent=label;group.appendChild(link)});toolbar.appendChild(group)}
function confirmDelete(msg){return confirm(msg||'Are you sure you want to delete this lead?')}
function playActionSound(type){try{const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;const ctx=new AudioContext();const notes=type==='upload'?[523.25,659.25,783.99]:[659.25,783.99];notes.forEach((frequency,index)=>{const oscillator=ctx.createOscillator();const gain=ctx.createGain();oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,ctx.currentTime+index*.09);gain.gain.exponentialRampToValueAtTime(.08,ctx.currentTime+index*.09+.02);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+index*.09+.16);oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start(ctx.currentTime+index*.09);oscillator.stop(ctx.currentTime+index*.09+.18)});setTimeout(()=>ctx.close(),500)}catch(e){}}
function addActionSounds(){const path=window.location.pathname;document.querySelectorAll('form[method="post"]').forEach(form=>{if((path==='/leads/new'||path.match(/^\/leads\/\d+$/))&&form.querySelector('input[name="full_name"]'))form.addEventListener('submit',()=>playActionSound('save'));if(path==='/import'&&form.querySelector('input[type="file"]'))form.addEventListener('submit',()=>playActionSound('upload'))})}
async function refreshDashboard(){const el=document.querySelector('[data-live-dashboard]');if(!el)return;try{const r=await fetch('/api/dashboard');if(!r.ok)return;const d=await r.json();document.querySelectorAll('[data-kpi="total"]').forEach(x=>x.textContent=d.total)}catch(e){}}
setInterval(refreshDashboard,30000);
addLeadContactActions();
addExportActions();
addActionSounds();
document.addEventListener('click',e=>{if(e.target.closest('.sidebar a')&&window.innerWidth<901)document.querySelector('.sidebar')?.classList.remove('open')})
